import { StyleSheet, Dimensions } from 'react-native'
import { C } from './constants'

export const { width } = Dimensions.get('window')

export const s = StyleSheet.create({
  flex:             { flex: 1 },
  orb1:             { position: 'absolute', top: -100, left: -80,   width: 320, height: 320, borderRadius: 160, backgroundColor: '#6B1E6A', opacity: 0.22 },
  orb2:             { position: 'absolute', top: 200,  right: -100, width: 250, height: 250, borderRadius: 125, backgroundColor: '#8C1848', opacity: 0.18 },
  orb3:             { position: 'absolute', bottom: 100, left: -60, width: 200, height: 200, borderRadius: 100, backgroundColor: '#4A1828', opacity: 0.18 },

  // Welcome / Auth
  heroSection:      { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 32, paddingTop: 60 },
  logoArea:         { alignItems: 'center', justifyContent: 'center', width: 130, height: 130, marginBottom: 32 },
  glowOrb:          { position: 'absolute', width: 130, height: 130, borderRadius: 65, backgroundColor: C.mauveGlow },
  logoRing:         { width: 100, height: 100, borderRadius: 50, borderWidth: 1.5, borderColor: C.mauve, alignItems: 'center', justifyContent: 'center' },
  logoCircle:       { width: 80, height: 80, borderRadius: 40, alignItems: 'center', justifyContent: 'center' },
  logoIcon:         { fontSize: 36, color: C.amberLight },
  heroTitle:        { fontSize: 48, fontWeight: '800', color: C.white, letterSpacing: 1.5, marginBottom: 16, textAlign: 'center' },
  heroTagline:      { fontSize: 26, fontWeight: '300', color: C.offWhite, textAlign: 'center', lineHeight: 38, marginBottom: 24 },
  heroDivider:      { width: 120, height: 1.5, marginBottom: 20 },
  heroBody:         { fontSize: 16, color: C.grey, textAlign: 'center', lineHeight: 26, maxWidth: 340 },
  ctaCard:          { width: '100%' },
  ctaGradient:      { paddingHorizontal: 28, paddingTop: 28, paddingBottom: 44, gap: 12 },

  btnPrimary:       { borderRadius: 16, paddingVertical: 19, alignItems: 'center' },
  btnPrimaryText:   { color: C.bg1, fontSize: 18, fontWeight: '700', letterSpacing: 0.5 },
  btnSecondary:     { borderWidth: 1, borderColor: C.mauve, borderRadius: 16, paddingVertical: 18, alignItems: 'center' },
  btnSecondaryText: { color: C.offWhite, fontSize: 17 },
  footerText:       { color: C.greyDim, fontSize: 13, textAlign: 'center', letterSpacing: 1.5, marginTop: 4 },
  addBtn:           { marginHorizontal: 20, marginBottom: 20 },

  authScroll:       { flexGrow: 1, paddingHorizontal: 24, paddingVertical: 60 },
  backBtn:          { marginBottom: 28 },
  backText:         { color: C.amber, fontSize: 17 },
  authTitle:        { fontSize: 38, fontWeight: '700', color: C.white, marginBottom: 8 },
  authSubtitle:     { fontSize: 17, color: C.grey, marginBottom: 32 },
  card:             { backgroundColor: '#4A1428CC', borderRadius: 24, padding: 24, borderWidth: 1, borderColor: C.mauveDim, marginBottom: 20 },
  fieldLabel:       { color: C.grey, fontSize: 13, fontWeight: '600', letterSpacing: 1.2, textTransform: 'uppercase', marginBottom: 10, marginTop: 4 },
  input:            { backgroundColor: '#1E1248', borderWidth: 1.5, borderColor: C.greyDim, borderRadius: 14, padding: 17, color: C.white, fontSize: 17, marginBottom: 20 },
  inputFocused:     { borderColor: C.amber },
  msgBox:           { borderRadius: 12, padding: 14, marginBottom: 12 },
  msgError:         { backgroundColor: '#FF8A8A18', borderWidth: 1, borderColor: '#FF8A8A44' },
  msgSuccess:       { backgroundColor: '#8AFFD418', borderWidth: 1, borderColor: '#8AFFD444' },
  switchLink:       { alignItems: 'center', paddingVertical: 8 },
  switchText:       { color: C.grey, fontSize: 16 },
  switchBold:       { color: C.amber, fontWeight: '600' },

  // Screen layout
  screenScroll:     { paddingBottom: 40 },

  // Home hero
  heroWrap:         { alignItems: 'center', paddingTop: 56, paddingBottom: 32, paddingHorizontal: 20 },
  heroCircle:       { width: 150, height: 150, borderRadius: 75, backgroundColor: C.mauveDim,
                      borderWidth: 2, borderColor: C.mauve + '80',
                      alignItems: 'center', justifyContent: 'center', marginBottom: 24 },
  heroCircleIcon:   { fontSize: 60 },
  homeGreeting:     { fontSize: 17, color: C.grey, marginBottom: 4 },
  homeName:         { fontSize: 34, fontWeight: '800', color: C.white, marginBottom: 8 },
  homeSubtitle:     { fontSize: 15, color: C.accent, opacity: 0.85 },

  // Stats row
  statsRow:         { flexDirection: 'row', paddingHorizontal: 20, gap: 10, marginBottom: 28 },
  statCard:         { flex: 1, backgroundColor: C.mauveDim + '55', borderRadius: 16, padding: 16,
                      alignItems: 'center', borderWidth: 1, borderColor: C.mauveDim },
  statValue:        { fontSize: 26, fontWeight: '700', color: C.accent },
  statLabel:        { fontSize: 12, color: C.grey, textAlign: 'center', marginTop: 3 },

  // Section headers
  sectionRow:       { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
                      paddingHorizontal: 20, marginBottom: 12, marginTop: 4 },
  sectionTitle:     { fontSize: 18, fontWeight: '600', color: C.offWhite },
  seeAll:           { fontSize: 14, color: C.grey },

  // Horizontal scroll cards (Home quick access)
  hScroll:          { paddingHorizontal: 20, paddingBottom: 4, gap: 12 },
  hCard:            { width: 120, backgroundColor: C.mauveDim + '55', borderRadius: 16,
                      padding: 16, borderWidth: 1, borderColor: C.mauveDim + '80' },
  hCardIcon:        { fontSize: 26, marginBottom: 10 },
  hCardTitle:       { fontSize: 13, fontWeight: '600', color: C.offWhite },
  hCardSub:         { fontSize: 11, color: C.grey, marginTop: 3 },

  // Page header (Vault / Memories / Family / Settings)
  pageHeaderPlain:  { paddingHorizontal: 24, paddingTop: 60, paddingBottom: 20 },
  pageTitle:        { fontSize: 30, fontWeight: '800', color: C.white, marginBottom: 4 },
  pageSubtitle:     { fontSize: 15, color: C.grey },

  // Filter pills (Vault)
  filterScroll:     { paddingHorizontal: 20, paddingBottom: 16, gap: 8 },
  filterPill:       { backgroundColor: C.mauveDim + '55', borderRadius: 24, paddingHorizontal: 18,
                      paddingVertical: 10, borderWidth: 1, borderColor: C.mauveDim },
  filterPillActive: { backgroundColor: C.mauve, borderColor: C.mauve },
  filterPillText:   { color: C.grey, fontSize: 20 },
  filterPillTextActive: { color: C.white, fontWeight: '600' },

  // List rows
  listRow:          { flexDirection: 'row', alignItems: 'center', backgroundColor: C.mauveDim + '33',
                      marginHorizontal: 20, marginBottom: 10, borderRadius: 16, padding: 16,
                      borderWidth: 1, borderColor: C.mauveDim + '80' },
  listIconWrap:     { width: 46, height: 46, borderRadius: 23, backgroundColor: C.mauveDim + '80',
                      alignItems: 'center', justifyContent: 'center', marginRight: 14 },
  listIcon:         { fontSize: 22 },
  listInfo:         { flex: 1 },
  listLabel:        { fontSize: 16, fontWeight: '600', color: C.offWhite, marginBottom: 2 },
  listDesc:         { fontSize: 13, color: C.grey },
  badge:            { backgroundColor: C.mauveDim, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4 },
  badgeText:        { color: C.offWhite, fontSize: 13, fontWeight: '600' },
  chevron:          { color: C.grey, fontSize: 18 },

  // Trusted contact row
  trustedRow:       { borderColor: C.mauve + '60', backgroundColor: C.mauve + '15' },
  trustedIconWrap:  { backgroundColor: C.mauve + '40' },
  trustedBadge:     { color: C.accent, fontSize: 12, marginTop: 4, fontWeight: '600' },

  // Edit / Delete icon buttons — 44×44pt minimum per Apple HIG / WCAG 2.5.5
  rowActions:       { flexDirection: 'row', gap: 8, alignItems: 'center' },
  editBtn:          { width: 44, height: 44, borderRadius: 12, backgroundColor: C.mauveDim + '80', alignItems: 'center', justifyContent: 'center' },
  editBtnIcon:      { fontSize: 20 },
  deleteBtn:        { width: 44, height: 44, borderRadius: 12, backgroundColor: C.amberDim + '33', alignItems: 'center', justifyContent: 'center' },
  deleteBtnIcon:    { fontSize: 20 },

  // Empty state
  emptyState:       { alignItems: 'center', paddingVertical: 48, paddingHorizontal: 32 },
  emptyIcon:        { fontSize: 48, marginBottom: 16 },
  emptyTitle:       { fontSize: 20, fontWeight: '600', color: C.offWhite, marginBottom: 8 },
  emptyDesc:        { fontSize: 15, color: C.grey, textAlign: 'center', lineHeight: 24 },

  // Tip card
  tipCard:          { backgroundColor: C.mauveDim + '44', borderRadius: 20, padding: 20,
                      marginHorizontal: 20, marginBottom: 20, borderWidth: 1, borderColor: C.mauveDim },
  tipTitle:         { fontSize: 16, fontWeight: '600', color: C.amberLight, marginBottom: 10 },
  tipBody:          { fontSize: 15, color: C.grey, lineHeight: 24 },
  tipLink:          { color: C.amber, fontSize: 15, marginTop: 12, fontWeight: '600' },

  // Settings

  // Estate Snapshot onboarding styles
  estateCard:        { backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 16, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', marginBottom: 14, overflow: 'hidden' },
  estateCardTop:     { flexDirection: 'row', alignItems: 'center', padding: 16, gap: 12 },
  estateCardIcon:    { fontSize: 28, width: 36, textAlign: 'center' },
  estateCardTitle:   { color: C.offWhite, fontSize: 15, fontWeight: '700', marginBottom: 2 },
  estateCardDesc:    { color: C.grey, fontSize: 13, lineHeight: 18 },
  estateToggleRow:   { flexDirection: 'row', gap: 6 },
  estateToggleBtn:   { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
  estateToggleText:  { color: C.grey, fontSize: 13, fontWeight: '600' },
  estateUploadArea:  { borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.08)', paddingHorizontal: 16, paddingBottom: 16, paddingTop: 12, gap: 8 },
  estateFileRow:     { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 8, padding: 8 },
  estateFileName:    { color: C.grey, fontSize: 13, flex: 1 },
  estateNotesInput:  { backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', color: C.offWhite, fontSize: 14, padding: 12, minHeight: 72, textAlignVertical: 'top' },
  estateUploadBtn:   { borderWidth: 1, borderColor: C.accent + '88', borderRadius: 10, paddingVertical: 10, alignItems: 'center' },
  estateUploadBtnText: { color: C.accent, fontSize: 14, fontWeight: '600' },

  paymentToast:     { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginHorizontal: 16, marginBottom: 8, padding: 14, borderRadius: 12, borderWidth: 1, borderColor: C.success + '44', backgroundColor: C.success + '11' },
  paymentToastText: { color: C.success, fontSize: 14, flex: 1, marginRight: 8 },
  sectionSpacer:     { height: 8 },
  signOutBtn:       { marginHorizontal: 20, marginTop: 24, borderWidth: 1, borderColor: '#FF8A8A44', borderRadius: 16, paddingVertical: 17, alignItems: 'center' },
  signOutText:      { color: C.amber, fontSize: 17, fontWeight: '600' },
  versionText:      { color: C.greyDim, textAlign: 'center', fontSize: 13, marginTop: 24, marginBottom: 8 },

  // ── Check-in Card ────────────────────────────────────────────────────────
  checkinCard:           { marginHorizontal: 20, marginBottom: 16, borderRadius: 18, borderWidth: 1, overflow: 'hidden', backgroundColor: 'rgba(255,255,255,0.04)' },
  checkinAlertBanner:    { backgroundColor: C.error + '22', paddingHorizontal: 16, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: C.error + '33' },
  checkinAlertText:      { color: C.error, fontSize: 13, fontWeight: '600', lineHeight: 18 },
  checkinCardInner:      { flexDirection: 'row', alignItems: 'center', padding: 16, gap: 14 },
  checkinLabel:          { fontSize: 14, fontWeight: '700', marginBottom: 3 },
  checkinSubtext:        { color: C.grey, fontSize: 13 },
  checkinLastText:       { color: C.greyDim, fontSize: 11, marginTop: 4 },
  checkinBtn:            { borderWidth: 1.5, borderRadius: 14, paddingHorizontal: 18, paddingVertical: 10, minWidth: 84, alignItems: 'center' },
  checkinBtnText:        { fontSize: 14, fontWeight: '700' },
  checkinFreqBtn:        { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, borderWidth: 1, borderColor: C.greyDim + '88' },
  checkinFreqBtnActive:  { backgroundColor: C.mauve, borderColor: C.mauve },
  checkinFreqText:       { color: C.grey, fontSize: 13, fontWeight: '600' },
  checkinFreqTextActive: { color: C.white },
  checkinStatusRow:      { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 4 },
  checkinStatusDot:      { color: C.success, fontSize: 10 },

  // ── Onboarding ────────────────────────────────────────────────────────────
  onboardScroll:       { flexGrow: 1, paddingHorizontal: 24, paddingTop: 56, paddingBottom: 48 },
  onboardHeader:       { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 28 },
  onboardLogoText:     { fontSize: 26, color: C.amberLight },
  onboardStep:         { color: C.grey, fontSize: 14, fontWeight: '600' },
  onboardTitle:        { fontSize: 32, fontWeight: '800', color: C.white, letterSpacing: -0.5, marginBottom: 12, lineHeight: 40 },
  onboardSubtitle:     { fontSize: 16, color: C.grey, lineHeight: 24, marginBottom: 32 },

  trackCard:           { borderRadius: 20, borderWidth: 1.5, padding: 20, marginBottom: 16, overflow: 'hidden' },
  trackCardGlow:       { position: 'absolute', top: -40, right: -40, width: 160, height: 160, borderRadius: 80 },
  trackCardTitle:      { fontSize: 18, fontWeight: '800', letterSpacing: -0.2 },
  trackCardBadge:      { fontSize: 11, fontWeight: '700', borderWidth: 1, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3, alignSelf: 'flex-start', marginTop: 4 },
  trackCardDesc:       { fontSize: 14, lineHeight: 22, marginBottom: 14 },
  trackFeatureRow:     { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginBottom: 6 },
  trackRadio:          { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: C.greyDim, alignItems: 'center', justifyContent: 'center' },
  trackRadioInner:     { width: 10, height: 10, borderRadius: 5, backgroundColor: C.bg1 },

  avatarPickerWrap:    { alignSelf: 'center', marginTop: 16, position: 'relative' },
  avatarPickerImg:     { width: 110, height: 110, borderRadius: 55, borderWidth: 2, borderColor: C.accent },
  avatarPickerPlaceholder: { width: 110, height: 110, borderRadius: 55, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: C.mauveDim } as any,
  avatarPickerBadge:   { position: 'absolute', bottom: 2, right: 2, width: 30, height: 30, borderRadius: 15, backgroundColor: C.mauveDim, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: C.bg2 },

  tourIconWrap:        { width: 120, height: 120, borderRadius: 60, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center', marginBottom: 28 },
  tourSlideTitle:      { fontSize: 28, fontWeight: '800', letterSpacing: -0.3, marginBottom: 18, textAlign: 'center' },
  tourSlideBody:       { fontSize: 16, color: C.grey, lineHeight: 26, textAlign: 'center', maxWidth: 340 },
  tourDots:            { flexDirection: 'row', justifyContent: 'center', gap: 8, marginBottom: 28 },
  tourDot:             { width: 8, height: 8, borderRadius: 4 },
  tourDotActive:       { width: 24, borderRadius: 4 },

  // ── Track pill (SettingsScreen) ───────────────────────────────────────────
  trackPill:           { flexDirection: 'row', alignItems: 'center', borderRadius: 20, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 8, alignSelf: 'flex-start' },

  // Tab bar
  tabBar:            { backgroundColor: C.bg2, borderTopColor: C.mauveDim, borderTopWidth: 1, paddingTop: 6, height: 82 },
  tabLabel:          { fontSize: 13, marginBottom: 4 },
  // Outer wrap: fixed size — focus state never compresses the icon
  tabIconWrap:       { width: 52, height: 40, alignItems: 'center', justifyContent: 'center' },
  // Inner pill: gets background on focus; emoji size is independent
  tabIconPill:       { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  tabIconPillActive: { backgroundColor: C.mauveDim + '70' },
  tabIconEmoji:      { fontSize: 24 },

  // Modals
  modalOverlay:     { flex: 1, justifyContent: 'flex-end', backgroundColor: '#00000088' },
  modalSheet:       { borderTopLeftRadius: 28, borderTopRightRadius: 28 },
  // Drag handle pill — first child inside modalInner (sits in top padding zone)
  modalHandle:      { width: 40, height: 5, borderRadius: 3, backgroundColor: 'rgba(61,16,32,0.2)',
                      alignSelf: 'center', marginTop: -28, marginBottom: 20 },
  modalInner:       { paddingHorizontal: 28, paddingTop: 40, paddingBottom: 28, maxHeight: 640 },
  modalHeader:      { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  modalTitle:       { fontSize: 22, fontWeight: '700', color: C.white },
  modalClose:       { color: C.grey, fontSize: 22, width: 44, height: 44, textAlign: 'center', lineHeight: 44 },
  // Option F close button — rounded square solid white
  modalCloseBtn:    { width: 36, height: 36, borderRadius: 10, backgroundColor: 'rgba(255,255,255,0.85)',
                      alignItems: 'center', justifyContent: 'center' },
  modalCloseX:      { color: '#3D1020', fontSize: 18, fontWeight: '700', lineHeight: 20 },

  chipBtn:          { borderWidth: 1, borderColor: C.greyDim, borderRadius: 20, paddingHorizontal: 14, paddingVertical: 8 },
  chipBtnActive:    { borderColor: C.amber, backgroundColor: C.amberDim + '40' },
  chipText:         { color: C.grey, fontSize: 13 },
  chipTextActive:   { color: C.amberLight, fontWeight: '600' },

  checkBox:         { width: 28, height: 28, borderRadius: 8, borderWidth: 1.5, borderColor: C.greyDim, alignItems: 'center', justifyContent: 'center' },
  checkBoxActive:   { backgroundColor: C.amber, borderColor: C.amber },

  passwordRow:           { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 6 },
  passwordToggle:        { width: 48, height: 48, borderRadius: 12, backgroundColor: C.mauveDim, alignItems: 'center', justifyContent: 'center' },
  passwordToggleIcon:    { fontSize: 22 },
  passwordHint:          { fontSize: 12, color: C.greyDim, marginBottom: 20 },
  filePickerBtn:         { backgroundColor: '#1E1248', borderWidth: 1.5, borderColor: C.greyDim, borderRadius: 14, borderStyle: 'dashed', padding: 16, marginBottom: 20 },
  filePickerContent:     { flexDirection: 'row', alignItems: 'center', gap: 12 },
  filePickerIcon:        { fontSize: 26 },
  filePickerName:        { color: C.offWhite, fontSize: 15, fontWeight: '600' },
  filePickerSize:        { color: C.grey, fontSize: 12, marginTop: 2 },
  filePickerPlaceholder: { color: C.greyDim, fontSize: 15 },
  removeFileBtn:         { backgroundColor: C.amberDim + '33', borderWidth: 1, borderColor: C.amber + '55', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 5 },
  removeFileBtnText:     { color: C.amberLight, fontSize: 13, fontWeight: '600' },
  replaceFileLink:       { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: C.greyDim + '44' },
  replaceFileLinkText:   { color: C.amber, fontSize: 13, textAlign: 'center' },

  // Memories
  memoryTypeGrid:    { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: 20, gap: 12, marginBottom: 8 },
  memoryTypeTile:    { width: (width - 64) / 2, backgroundColor: C.mauveDim + '44', borderRadius: 20, padding: 24,
                       alignItems: 'center', borderWidth: 1, borderColor: C.mauveDim + '80', gap: 10, position: 'relative' },
  memoryTypeTileDim: { opacity: 0.5 },
  memoryTypeIcon:    { fontSize: 64 },
  memoryTypeLabel:   { fontSize: 16, fontWeight: '600', color: C.offWhite, textAlign: 'center' },
  comingSoonBadge:   { position: 'absolute', top: 10, right: 10, backgroundColor: C.mauveDim,
                       borderRadius: 8, paddingHorizontal: 7, paddingVertical: 3 },
  comingSoonText:    { color: C.grey, fontSize: 11, fontWeight: '600' },
  storyInput:        { height: 200, textAlignVertical: 'top', lineHeight: 26 },
  wordCountRow:      { flexDirection: 'row', justifyContent: 'flex-end', marginTop: -12, marginBottom: 16 },
  wordCount:         { color: C.greyDim, fontSize: 13 },
  storyReadText:     { color: C.offWhite, fontSize: 17, lineHeight: 30, paddingBottom: 32 },

  // Schedule button
  scheduleBtn:      { width: 48, height: 48, borderRadius: 24, backgroundColor: C.mauveDim, alignItems: 'center', justifyContent: 'center' },
  scheduleBtnIcon:  { fontSize: 26 },
  scheduledBadge:   { width: 48, height: 48, borderRadius: 24, backgroundColor: C.success + '22', alignItems: 'center', justifyContent: 'center' },
  scheduledBadgeIcon: { fontSize: 22 },
  famChipCheck:     { position: 'absolute', top: 4, right: 4, fontSize: 10, color: C.success, fontWeight: '700' },

  // Time Capsule list
  capsuleRow:       { flexDirection: 'row', alignItems: 'flex-start', backgroundColor: C.mauveDim + '22',
                      marginHorizontal: 20, marginBottom: 10, borderRadius: 16, padding: 14,
                      borderWidth: 1, borderColor: C.accent + '33' },
  capsuleLeft:      { flex: 1, flexDirection: 'row', gap: 12, alignItems: 'flex-start' },
  capsuleTitle:     { fontSize: 14, fontWeight: '600', color: C.offWhite, marginBottom: 2 },
  capsuleRecipient: { fontSize: 13, color: C.accent },
  capsuleDate:      { fontSize: 12, color: C.grey },
  capsuleNote:      { fontSize: 12, color: C.greyDim, marginTop: 3 },
  capsuleStatusPill:{ backgroundColor: C.amber + '33', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 2 },
  capsuleStatusText:{ color: C.amber, fontSize: 10, fontWeight: '600', textTransform: 'capitalize' },
  capsuleCancel:    { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  capsuleCancelText:{ color: C.greyDim, fontSize: 20 },

  // Schedule modal
  scheduleMemPreview: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: C.mauveDim + '44',
                        borderRadius: 14, padding: 14, marginBottom: 20, borderWidth: 1, borderColor: C.mauveDim },
  scheduleMemIcon:    { fontSize: 30 },
  scheduleMemTitle:   { fontSize: 16, fontWeight: '600', color: C.offWhite },
  scheduleMemType:    { fontSize: 12, color: C.grey, marginTop: 2 },
  scheduleEmptyFam:   { backgroundColor: C.mauveDim + '44', borderRadius: 12, padding: 16, marginBottom: 20, alignItems: 'center' },
  famChip:            { alignItems: 'center', gap: 6, padding: 12, borderRadius: 14,
                        borderWidth: 1, borderColor: C.greyDim, minWidth: 70 },
  famChipActive:      { borderColor: C.accent, backgroundColor: C.accent + '22' },
  famChipAvatar:      { width: 40, height: 40, borderRadius: 20, backgroundColor: C.mauveDim,
                        textAlign: 'center', lineHeight: 36, fontSize: 16, fontWeight: '700', color: C.offWhite },
  famChipName:        { fontSize: 13, color: C.grey, fontWeight: '500' },
  famChipNameActive:  { color: C.accent, fontWeight: '600' },
  datePicker:         { flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
                        backgroundColor: C.mauveDim + '44', borderRadius: 16, padding: 16, marginBottom: 8,
                        borderWidth: 1, borderColor: C.mauveDim, gap: 8 },
  dateCol:            { alignItems: 'center', gap: 8, minWidth: 64 },
  dateArrow:          { color: C.accent, fontSize: 16, fontWeight: '700' },
  dateVal:            { fontSize: 22, fontWeight: '700', color: C.white, minWidth: 64, textAlign: 'center' },
  dateSep:            { color: C.greyDim, fontSize: 22, fontWeight: '300', marginBottom: 4 },
  datePreview:        { color: C.grey, fontSize: 13, textAlign: 'center', marginBottom: 4 },
  scheduleDisclaimer: { color: C.greyDim, fontSize: 12, textAlign: 'center', lineHeight: 18, marginTop: 12, marginBottom: 8 },

  // Voice memo
  voiceCenter:    { alignItems: 'center', paddingVertical: 16, width: '100%' },
  recRingOuter:   { width: 120, height: 120, borderRadius: 60, backgroundColor: C.error + '22',
                    alignItems: 'center', justifyContent: 'center', marginBottom: 20 },
  recBtn:         { width: 96, height: 96, borderRadius: 48, backgroundColor: C.mauveDim,
                    alignItems: 'center', justifyContent: 'center',
                    borderWidth: 2, borderColor: C.mauve },
  recBtnActive:   { backgroundColor: C.error + 'CC', borderColor: C.error },
  recBtnIcon:     { fontSize: 36 },
  recTimer:       { fontSize: 38, fontWeight: '700', color: C.white, letterSpacing: 2, marginBottom: 8 },
  recHint:        { fontSize: 14, color: C.grey },
  recDoneWrap:    { alignItems: 'center', marginBottom: 8 },
  recDoneIcon:    { fontSize: 36, marginBottom: 8 },
  recDoneText:    { fontSize: 16, fontWeight: '600', color: C.success, marginBottom: 6 },
  recRetake:      { color: C.amber, fontSize: 14, fontWeight: '600' },
  playBtn:        { width: 44, height: 44, borderRadius: 22, backgroundColor: C.mauve,
                    alignItems: 'center', justifyContent: 'center' },
  playBtnIcon:    { fontSize: 18, color: C.white },
  durationText:   { color: C.grey, fontSize: 12, fontWeight: '600' },

  // Photo album
  photoCountBadge:    { backgroundColor: C.mauveDim, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 3 },
  photoCountText:     { color: C.accent, fontSize: 12, fontWeight: '600' },
  photoAddBtn:        { flex: 1, alignItems: 'center', gap: 6, backgroundColor: C.mauveDim + '88',
                        borderRadius: 14, padding: 16, borderWidth: 1, borderColor: C.mauveDim },
  photoAddBtnIcon:    { fontSize: 26 },
  photoAddBtnLabel:   { fontSize: 13, fontWeight: '600', color: C.offWhite, textAlign: 'center' },
  photoDraftCard:     { width: 120, borderRadius: 12, overflow: 'hidden', backgroundColor: C.mauveDim },
  photoDraftThumb:    { width: 120, height: 120 },
  photoDraftRemove:   { position: 'absolute', top: 4, right: 4, width: 30, height: 30, borderRadius: 15,
                        backgroundColor: '#00000099', alignItems: 'center', justifyContent: 'center' },
  photoDraftCaption:  { fontSize: 12, color: C.offWhite, padding: 8, backgroundColor: C.bg1 + 'CC' },
  uploadProgressWrap: { backgroundColor: C.mauveDim + '44', borderRadius: 8, height: 28, overflow: 'hidden',
                        marginBottom: 14, position: 'relative', justifyContent: 'center' },
  uploadProgressBar:  { position: 'absolute', left: 0, top: 0, bottom: 0, backgroundColor: C.amber + '88', borderRadius: 8 },
  uploadProgressText: { color: C.offWhite, fontSize: 12, fontWeight: '600', textAlign: 'center', zIndex: 1 },

  // Album detail viewer
  albumDetailOverlay: { flex: 1, backgroundColor: C.bg1 },
  albumDetailHeader:  { flexDirection: 'row', alignItems: 'flex-start', paddingHorizontal: 20,
                        paddingTop: 56, paddingBottom: 16, gap: 12, borderBottomWidth: 1, borderBottomColor: C.mauveDim },
  albumDetailTitle:   { fontSize: 20, fontWeight: '700', color: C.offWhite, marginBottom: 4 },
  albumDetailDesc:    { fontSize: 14, color: C.grey, lineHeight: 20 },
  albumGrid:          { flexDirection: 'row', flexWrap: 'wrap', padding: 2, paddingBottom: 40 },
  albumGridCell:      { width: (width - 4) / 2, padding: 2 },
  albumGridImg:       { width: '100%', height: 180, borderRadius: 4 },
  albumGridCaption:   { backgroundColor: '#00000088', paddingHorizontal: 8, paddingVertical: 5, marginTop: -28, borderBottomLeftRadius: 4, borderBottomRightRadius: 4 },
  albumGridCaptionText:{ color: C.white, fontSize: 11, lineHeight: 15 },

  // Fullscreen photo
  fullscreenOverlay:  { flex: 1, backgroundColor: '#000000F2', justifyContent: 'center', alignItems: 'center' },
  fullscreenClose:    { position: 'absolute', top: 52, right: 20, width: 44, height: 44, borderRadius: 22,
                        backgroundColor: C.mauveDim, alignItems: 'center', justifyContent: 'center', zIndex: 10 },
  fullscreenImg:      { width: '100%', height: '75%' },
  fullscreenCaption:  { position: 'absolute', bottom: 60, left: 20, right: 20,
                        backgroundColor: '#00000099', borderRadius: 12, padding: 14 },
  fullscreenCaptionText:{ color: C.white, fontSize: 15, lineHeight: 22, textAlign: 'center' },

  // Video pick modal
  videoPickWrap:      { alignItems: 'center', paddingVertical: 8, width: '100%' },
  videoPickHint:      { color: C.grey, fontSize: 14, textAlign: 'center', lineHeight: 20, marginBottom: 24 },
  videoPickBtn:       { flexDirection: 'row', alignItems: 'center', gap: 14,
                        backgroundColor: C.mauveDim + '88', borderRadius: 16, padding: 18,
                        marginBottom: 12, width: '100%',
                        borderWidth: 1, borderColor: C.mauveDim },
  videoPickBtnDisabled: { opacity: 0.45, borderColor: C.greyDim },
  videoPickBtnIcon:   { fontSize: 28 },
  videoPickBtnLabel:  { fontSize: 16, fontWeight: '600', color: C.offWhite, marginBottom: 2 },
  videoPickBtnSub:    { fontSize: 13, color: C.grey },
  videoReadyBadge:    { flexDirection: 'row', alignItems: 'center', gap: 12,
                        backgroundColor: C.success + '22', borderRadius: 14, padding: 16,
                        borderWidth: 1, borderColor: C.success + '44' },
  videoReadyIcon:     { fontSize: 28 },
  videoReadyText:     { fontSize: 15, fontWeight: '600', color: C.success },
  videoReadyDur:      { fontSize: 13, color: C.grey, marginTop: 2 },
  videoPlayBtn:       { width: 44, height: 44, borderRadius: 22, backgroundColor: C.amber + 'CC',
                        alignItems: 'center', justifyContent: 'center' },

  // Full-screen video player
  videoPlayerOverlay: { flex: 1, backgroundColor: '#000000EE', justifyContent: 'center' },
  videoPlayerHeader:  { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20,
                        paddingTop: 56, paddingBottom: 16, gap: 12 },
  videoPlayerTitle:   { flex: 1, fontSize: 18, fontWeight: '700', color: C.offWhite },
  videoPlayerCloseBtn:{ width: 44, height: 44, borderRadius: 22, backgroundColor: C.mauveDim,
                        alignItems: 'center', justifyContent: 'center' },
  videoPlayerCloseIcon:{ fontSize: 18, color: C.offWhite, fontWeight: '700' },
  videoPlayerVideo:   { width: '100%', height: 320 },
  videoPlayerDur:     { color: C.grey, fontSize: 13, textAlign: 'center', marginTop: 12 },

  // Plan banners (settings)
  premiumBanner:        { marginHorizontal: 20, marginBottom: 20, borderRadius: 18, overflow: 'hidden' },
  premiumBannerInner:   { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
                          padding: 18, borderWidth: 1, borderColor: C.accent + '55', borderRadius: 18 },
  premiumBannerLeft:    { flexDirection: 'row', alignItems: 'center', gap: 12 },
  premiumBannerCrown:   { fontSize: 28 },
  premiumBannerTitle:   { fontSize: 16, fontWeight: '700', color: C.offWhite },
  premiumBannerSub:     { fontSize: 12, color: C.accent, marginTop: 2 },
  premiumActivePill:    { backgroundColor: C.success + '33', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 4,
                          borderWidth: 1, borderColor: C.success + '55' },
  premiumActivePillText:{ color: C.success, fontSize: 12, fontWeight: '700' },
  upgradeBanner:        { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
                          padding: 18, borderRadius: 18 },
  upgradeBannerLeft:    { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  upgradeBannerIcon:    { fontSize: 26 },
  upgradeBannerTitle:   { fontSize: 15, fontWeight: '700', color: C.bg1 },
  upgradeBannerSub:     { fontSize: 12, color: C.bg1 + 'CC', marginTop: 2 },

  // Upgrade modal
  upgradeModalTitle:    { fontSize: 22, fontWeight: '800', color: C.offWhite, letterSpacing: -0.3 },
  billingToggleWrap:    { flexDirection: 'row', backgroundColor: C.mauveDim + '44', borderRadius: 14,
                          padding: 4, marginBottom: 20, borderWidth: 1, borderColor: C.mauveDim },
  billingToggleBtn:     { flex: 1, paddingVertical: 10, borderRadius: 10, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 6 },
  billingToggleBtnActive:{ backgroundColor: C.mauve },
  billingToggleText:    { color: C.grey, fontSize: 14, fontWeight: '600' },
  billingToggleTextActive:{ color: C.white },
  saveBadge:            { backgroundColor: C.success + '44', borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },
  saveBadgeText:        { color: C.success, fontSize: 10, fontWeight: '700' },

  // Billing tab row (4 tabs: monthly/annual/legacy/gift)
  billingTab:           { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 10, paddingHorizontal: 16,
                          borderRadius: 22, borderWidth: 1, borderColor: C.greyDim + '66', backgroundColor: C.mauveDim + '33' },
  billingTabActive:     { backgroundColor: C.mauve, borderColor: C.accent + '66' },
  billingTabText:       { color: C.grey, fontSize: 14, fontWeight: '600' },
  billingTabTextActive: { color: C.white },

  // Plan cards
  planCard:             { backgroundColor: C.mauveDim + '55', borderRadius: 18, padding: 20,
                          marginBottom: 14, borderWidth: 1, borderColor: C.mauveDim },
  planCardPremium:      { borderRadius: 18, padding: 20, marginBottom: 8,
                          borderWidth: 1.5, borderColor: C.accent + '88', overflow: 'hidden' },
  premiumGlow:          { position: 'absolute', top: -40, right: -40, width: 140, height: 140,
                          borderRadius: 70, backgroundColor: C.accent + '22' },
  planCardHeader:       { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 16 },
  planCardName:         { fontSize: 18, fontWeight: '800', color: C.offWhite, letterSpacing: -0.2 },
  planCardPrice:        { fontSize: 26, fontWeight: '800', color: C.white, letterSpacing: -0.5 },
  planCardCurrent:      { marginTop: 16, backgroundColor: C.mauveDim, borderRadius: 10,
                          paddingVertical: 8, alignItems: 'center', borderWidth: 1, borderColor: C.greyDim },
  planCardCurrentText:  { color: C.grey, fontSize: 13, fontWeight: '600' },
  featureRow:           { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  featureCheck:         { fontSize: 14, fontWeight: '700', width: 16, textAlign: 'center' },
  featureLabel:         { fontSize: 14, color: C.grey, flex: 1, lineHeight: 20 },
  upgradeDisclaimer:    { color: C.greyDim, fontSize: 12, textAlign: 'center', marginTop: 8, marginBottom: 20, lineHeight: 18 },

  // Confirm dialogs
  confirmOverlay:   { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#00000099', padding: 28 },
  confirmBox:       { width: '100%', borderRadius: 24, overflow: 'hidden' },
  confirmInner:     { padding: 28, alignItems: 'center' },
  confirmIcon:      { fontSize: 40, marginBottom: 12 },
  confirmTitle:     { fontSize: 22, fontWeight: '700', color: C.white, marginBottom: 10 },
  confirmBody:      { fontSize: 15, color: C.grey, textAlign: 'center', lineHeight: 24, marginBottom: 24 },
  confirmActions:   { flexDirection: 'row', gap: 12, width: '100%' },
  confirmCancel:    { flex: 1, borderWidth: 1, borderColor: C.mauveDim, borderRadius: 14, paddingVertical: 15, alignItems: 'center' },
  confirmCancelText:{ color: C.offWhite, fontSize: 16, fontWeight: '600' },
  confirmDelete:    { flex: 1, backgroundColor: C.amberDim + '44', borderWidth: 1, borderColor: C.amber + '66', borderRadius: 14, paddingVertical: 15, alignItems: 'center' },
  confirmDeleteText:{ color: C.amberLight, fontSize: 16, fontWeight: '700' },
})
